// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/maranet.proto

package maranetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED CommandType = 0
	CommandType_COMMAND_CREATE_PEER      CommandType = 1
	CommandType_COMMAND_REMOVE_PEER      CommandType = 2
	CommandType_COMMAND_UPDATE_PEER      CommandType = 3
	CommandType_COMMAND_UPDATE_CONFIG    CommandType = 4
	CommandType_COMMAND_RESTART          CommandType = 5
	CommandType_COMMAND_SHUTDOWN         CommandType = 6
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "COMMAND_CREATE_PEER",
		2: "COMMAND_REMOVE_PEER",
		3: "COMMAND_UPDATE_PEER",
		4: "COMMAND_UPDATE_CONFIG",
		5: "COMMAND_RESTART",
		6: "COMMAND_SHUTDOWN",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED": 0,
		"COMMAND_CREATE_PEER":      1,
		"COMMAND_REMOVE_PEER":      2,
		"COMMAND_UPDATE_PEER":      3,
		"COMMAND_UPDATE_CONFIG":    4,
		"COMMAND_RESTART":          5,
		"COMMAND_SHUTDOWN":         6,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_maranet_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_proto_maranet_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{0}
}

type PeerEventType int32

const (
	PeerEventType_PEER_EVENT_UNSPECIFIED PeerEventType = 0
	PeerEventType_PEER_CONNECTED         PeerEventType = 1
	PeerEventType_PEER_DISCONNECTED      PeerEventType = 2
	PeerEventType_PEER_EXPIRED           PeerEventType = 3
	PeerEventType_PEER_HANDSHAKE_FAILED  PeerEventType = 4
)

// Enum value maps for PeerEventType.
var (
	PeerEventType_name = map[int32]string{
		0: "PEER_EVENT_UNSPECIFIED",
		1: "PEER_CONNECTED",
		2: "PEER_DISCONNECTED",
		3: "PEER_EXPIRED",
		4: "PEER_HANDSHAKE_FAILED",
	}
	PeerEventType_value = map[string]int32{
		"PEER_EVENT_UNSPECIFIED": 0,
		"PEER_CONNECTED":         1,
		"PEER_DISCONNECTED":      2,
		"PEER_EXPIRED":           3,
		"PEER_HANDSHAKE_FAILED":  4,
	}
)

func (x PeerEventType) Enum() *PeerEventType {
	p := new(PeerEventType)
	*p = x
	return p
}

func (x PeerEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_maranet_proto_enumTypes[1].Descriptor()
}

func (PeerEventType) Type() protoreflect.EnumType {
	return &file_proto_maranet_proto_enumTypes[1]
}

func (x PeerEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerEventType.Descriptor instead.
func (PeerEventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{1}
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`  // public IP:port of the node
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`  // geographic location
	Capacity      int32                  `protobuf:"varint,5,opt,name=capacity,proto3" json:"capacity,omitempty"` // max peers this node can handle
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`    // agent version
	Platform      string                 `protobuf:"bytes,7,opt,name=platform,proto3" json:"platform,omitempty"`  // rpi, vps, android
	Capabilities  *NodeCapabilities      `protobuf:"bytes,8,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_proto_maranet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNodeRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterNodeRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RegisterNodeRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisterNodeRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *RegisterNodeRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *RegisterNodeRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterNodeRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RegisterNodeRequest) GetCapabilities() *NodeCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type NodeCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BandwidthMbps int64                  `protobuf:"varint,1,opt,name=bandwidth_mbps,json=bandwidthMbps,proto3" json:"bandwidth_mbps,omitempty"`
	MemoryMb      int64                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	CpuCores      int32                  `protobuf:"varint,3,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	Ipv6Support   bool                   `protobuf:"varint,4,opt,name=ipv6_support,json=ipv6Support,proto3" json:"ipv6_support,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCapabilities) Reset() {
	*x = NodeCapabilities{}
	mi := &file_proto_maranet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCapabilities) ProtoMessage() {}

func (x *NodeCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCapabilities.ProtoReflect.Descriptor instead.
func (*NodeCapabilities) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{1}
}

func (x *NodeCapabilities) GetBandwidthMbps() int64 {
	if x != nil {
		return x.BandwidthMbps
	}
	return 0
}

func (x *NodeCapabilities) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *NodeCapabilities) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *NodeCapabilities) GetIpv6Support() bool {
	if x != nil {
		return x.Ipv6Support
	}
	return false
}

type RegisterNodeResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NodeId               string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ServerPublicKey      string                 `protobuf:"bytes,2,opt,name=server_public_key,json=serverPublicKey,proto3" json:"server_public_key,omitempty"`
	ServerEndpoint       string                 `protobuf:"bytes,3,opt,name=server_endpoint,json=serverEndpoint,proto3" json:"server_endpoint,omitempty"`
	AssignedSubnet       string                 `protobuf:"bytes,4,opt,name=assigned_subnet,json=assignedSubnet,proto3" json:"assigned_subnet,omitempty"` // e.g. 10.0.1.0/24
	TunnelConfig         string                 `protobuf:"bytes,5,opt,name=tunnel_config,json=tunnelConfig,proto3" json:"tunnel_config,omitempty"`       // WireGuard config for node-to-server tunnel
	HeartbeatIntervalSec int32                  `protobuf:"varint,6,opt,name=heartbeat_interval_sec,json=heartbeatIntervalSec,proto3" json:"heartbeat_interval_sec,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_proto_maranet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeResponse) GetServerPublicKey() string {
	if x != nil {
		return x.ServerPublicKey
	}
	return ""
}

func (x *RegisterNodeResponse) GetServerEndpoint() string {
	if x != nil {
		return x.ServerEndpoint
	}
	return ""
}

func (x *RegisterNodeResponse) GetAssignedSubnet() string {
	if x != nil {
		return x.AssignedSubnet
	}
	return ""
}

func (x *RegisterNodeResponse) GetTunnelConfig() string {
	if x != nil {
		return x.TunnelConfig
	}
	return ""
}

func (x *RegisterNodeResponse) GetHeartbeatIntervalSec() int32 {
	if x != nil {
		return x.HeartbeatIntervalSec
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ActivePeers   int32                  `protobuf:"varint,2,opt,name=active_peers,json=activePeers,proto3" json:"active_peers,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	BytesRx       int64                  `protobuf:"varint,5,opt,name=bytes_rx,json=bytesRx,proto3" json:"bytes_rx,omitempty"`
	BytesTx       int64                  `protobuf:"varint,6,opt,name=bytes_tx,json=bytesTx,proto3" json:"bytes_tx,omitempty"`
	UptimeSeconds float64                `protobuf:"fixed64,7,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_maranet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetActivePeers() int32 {
	if x != nil {
		return x.ActivePeers
	}
	return 0
}

func (x *HeartbeatRequest) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HeartbeatRequest) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *HeartbeatRequest) GetBytesRx() int64 {
	if x != nil {
		return x.BytesRx
	}
	return 0
}

func (x *HeartbeatRequest) GetBytesTx() int64 {
	if x != nil {
		return x.BytesTx
	}
	return 0
}

func (x *HeartbeatRequest) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged    bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	PendingCommands []*PendingCommand      `protobuf:"bytes,2,rep,name=pending_commands,json=pendingCommands,proto3" json:"pending_commands,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_maranet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetPendingCommands() []*PendingCommand {
	if x != nil {
		return x.PendingCommands
	}
	return nil
}

type PendingCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Type          CommandType            `protobuf:"varint,2,opt,name=type,proto3,enum=maranet.CommandType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingCommand) Reset() {
	*x = PendingCommand{}
	mi := &file_proto_maranet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingCommand) ProtoMessage() {}

func (x *PendingCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingCommand.ProtoReflect.Descriptor instead.
func (*PendingCommand) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{5}
}

func (x *PendingCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *PendingCommand) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *PendingCommand) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CreatePeerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,3,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	PublicKey      string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // user's WireGuard public key
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	AllowedIps     string                 `protobuf:"bytes,6,opt,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"` // CIDR for this peer
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePeerRequest) Reset() {
	*x = CreatePeerRequest{}
	mi := &file_proto_maranet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePeerRequest) ProtoMessage() {}

func (x *CreatePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePeerRequest.ProtoReflect.Descriptor instead.
func (*CreatePeerRequest) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePeerRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CreatePeerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePeerRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *CreatePeerRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *CreatePeerRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CreatePeerRequest) GetAllowedIps() string {
	if x != nil {
		return x.AllowedIps
	}
	return ""
}

type CreatePeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PeerIp        string                 `protobuf:"bytes,2,opt,name=peer_ip,json=peerIp,proto3" json:"peer_ip,omitempty"`                        // assigned IP for the user
	NodeEndpoint  string                 `protobuf:"bytes,3,opt,name=node_endpoint,json=nodeEndpoint,proto3" json:"node_endpoint,omitempty"`      // node's public endpoint
	NodePublicKey string                 `protobuf:"bytes,4,opt,name=node_public_key,json=nodePublicKey,proto3" json:"node_public_key,omitempty"` // node's WG public key
	DnsServers    string                 `protobuf:"bytes,5,opt,name=dns_servers,json=dnsServers,proto3" json:"dns_servers,omitempty"`            // DNS servers to use
	Keepalive     int32                  `protobuf:"varint,6,opt,name=keepalive,proto3" json:"keepalive,omitempty"`                               // persistent keepalive interval
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePeerResponse) Reset() {
	*x = CreatePeerResponse{}
	mi := &file_proto_maranet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePeerResponse) ProtoMessage() {}

func (x *CreatePeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePeerResponse.ProtoReflect.Descriptor instead.
func (*CreatePeerResponse) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{7}
}

func (x *CreatePeerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreatePeerResponse) GetPeerIp() string {
	if x != nil {
		return x.PeerIp
	}
	return ""
}

func (x *CreatePeerResponse) GetNodeEndpoint() string {
	if x != nil {
		return x.NodeEndpoint
	}
	return ""
}

func (x *CreatePeerResponse) GetNodePublicKey() string {
	if x != nil {
		return x.NodePublicKey
	}
	return ""
}

func (x *CreatePeerResponse) GetDnsServers() string {
	if x != nil {
		return x.DnsServers
	}
	return ""
}

func (x *CreatePeerResponse) GetKeepalive() int32 {
	if x != nil {
		return x.Keepalive
	}
	return 0
}

func (x *CreatePeerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RemovePeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePeerRequest) Reset() {
	*x = RemovePeerRequest{}
	mi := &file_proto_maranet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeerRequest) ProtoMessage() {}

func (x *RemovePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePeerRequest.ProtoReflect.Descriptor instead.
func (*RemovePeerRequest) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{8}
}

func (x *RemovePeerRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RemovePeerRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RemovePeerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemovePeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePeerResponse) Reset() {
	*x = RemovePeerResponse{}
	mi := &file_proto_maranet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeerResponse) ProtoMessage() {}

func (x *RemovePeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePeerResponse.ProtoReflect.Descriptor instead.
func (*RemovePeerResponse) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{9}
}

func (x *RemovePeerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemovePeerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdatePeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=new_expires_at,json=newExpiresAt,proto3" json:"new_expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePeerRequest) Reset() {
	*x = UpdatePeerRequest{}
	mi := &file_proto_maranet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePeerRequest) ProtoMessage() {}

func (x *UpdatePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePeerRequest.ProtoReflect.Descriptor instead.
func (*UpdatePeerRequest) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePeerRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UpdatePeerRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *UpdatePeerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePeerRequest) GetNewExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NewExpiresAt
	}
	return nil
}

type UpdatePeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePeerResponse) Reset() {
	*x = UpdatePeerResponse{}
	mi := &file_proto_maranet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePeerResponse) ProtoMessage() {}

func (x *UpdatePeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePeerResponse.ProtoReflect.Descriptor instead.
func (*UpdatePeerResponse) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{11}
}

func (x *UpdatePeerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdatePeerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersRequest) Reset() {
	*x = ListPeersRequest{}
	mi := &file_proto_maranet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersRequest) ProtoMessage() {}

func (x *ListPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersRequest.ProtoReflect.Descriptor instead.
func (*ListPeersRequest) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{12}
}

func (x *ListPeersRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ListPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersResponse) Reset() {
	*x = ListPeersResponse{}
	mi := &file_proto_maranet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersResponse) ProtoMessage() {}

func (x *ListPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersResponse.ProtoReflect.Descriptor instead.
func (*ListPeersResponse) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{13}
}

func (x *ListPeersResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type PeerInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PublicKey      string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,3,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	AllowedIps     string                 `protobuf:"bytes,4,opt,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	BytesRx        int64                  `protobuf:"varint,5,opt,name=bytes_rx,json=bytesRx,proto3" json:"bytes_rx,omitempty"`
	BytesTx        int64                  `protobuf:"varint,6,opt,name=bytes_tx,json=bytesTx,proto3" json:"bytes_tx,omitempty"`
	LastHandshake  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_handshake,json=lastHandshake,proto3" json:"last_handshake,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_proto_maranet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{14}
}

func (x *PeerInfo) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *PeerInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PeerInfo) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *PeerInfo) GetAllowedIps() string {
	if x != nil {
		return x.AllowedIps
	}
	return ""
}

func (x *PeerInfo) GetBytesRx() int64 {
	if x != nil {
		return x.BytesRx
	}
	return 0
}

func (x *PeerInfo) GetBytesTx() int64 {
	if x != nil {
		return x.BytesTx
	}
	return 0
}

func (x *PeerInfo) GetLastHandshake() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHandshake
	}
	return nil
}

func (x *PeerInfo) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type NodeMessage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*NodeMessage_Heartbeat
	//	*NodeMessage_CommandAck
	//	*NodeMessage_PeerEvent
	//	*NodeMessage_Error
	Message       isNodeMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_proto_maranet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{15}
}

func (x *NodeMessage) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeMessage) GetMessage() isNodeMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *NodeMessage) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Message.(*NodeMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *NodeMessage) GetCommandAck() *CommandAck {
	if x != nil {
		if x, ok := x.Message.(*NodeMessage_CommandAck); ok {
			return x.CommandAck
		}
	}
	return nil
}

func (x *NodeMessage) GetPeerEvent() *PeerEvent {
	if x != nil {
		if x, ok := x.Message.(*NodeMessage_PeerEvent); ok {
			return x.PeerEvent
		}
	}
	return nil
}

func (x *NodeMessage) GetError() *NodeError {
	if x != nil {
		if x, ok := x.Message.(*NodeMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isNodeMessage_Message interface {
	isNodeMessage_Message()
}

type NodeMessage_Heartbeat struct {
	Heartbeat *HeartbeatRequest `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type NodeMessage_CommandAck struct {
	CommandAck *CommandAck `protobuf:"bytes,3,opt,name=command_ack,json=commandAck,proto3,oneof"`
}

type NodeMessage_PeerEvent struct {
	PeerEvent *PeerEvent `protobuf:"bytes,4,opt,name=peer_event,json=peerEvent,proto3,oneof"`
}

type NodeMessage_Error struct {
	Error *NodeError `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*NodeMessage_Heartbeat) isNodeMessage_Message() {}

func (*NodeMessage_CommandAck) isNodeMessage_Message() {}

func (*NodeMessage_PeerEvent) isNodeMessage_Message() {}

func (*NodeMessage_Error) isNodeMessage_Message() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerMessage_HeartbeatAck
	//	*ServerMessage_CreatePeer
	//	*ServerMessage_RemovePeer
	//	*ServerMessage_UpdatePeer
	//	*ServerMessage_ConfigUpdate
	Message       isServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_maranet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{16}
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetHeartbeatAck() *HeartbeatResponse {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *ServerMessage) GetCreatePeer() *CreatePeerRequest {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_CreatePeer); ok {
			return x.CreatePeer
		}
	}
	return nil
}

func (x *ServerMessage) GetRemovePeer() *RemovePeerRequest {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_RemovePeer); ok {
			return x.RemovePeer
		}
	}
	return nil
}

func (x *ServerMessage) GetUpdatePeer() *UpdatePeerRequest {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_UpdatePeer); ok {
			return x.UpdatePeer
		}
	}
	return nil
}

func (x *ServerMessage) GetConfigUpdate() *ConfigUpdate {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_ConfigUpdate); ok {
			return x.ConfigUpdate
		}
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_HeartbeatAck struct {
	HeartbeatAck *HeartbeatResponse `protobuf:"bytes,1,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type ServerMessage_CreatePeer struct {
	CreatePeer *CreatePeerRequest `protobuf:"bytes,2,opt,name=create_peer,json=createPeer,proto3,oneof"`
}

type ServerMessage_RemovePeer struct {
	RemovePeer *RemovePeerRequest `protobuf:"bytes,3,opt,name=remove_peer,json=removePeer,proto3,oneof"`
}

type ServerMessage_UpdatePeer struct {
	UpdatePeer *UpdatePeerRequest `protobuf:"bytes,4,opt,name=update_peer,json=updatePeer,proto3,oneof"`
}

type ServerMessage_ConfigUpdate struct {
	ConfigUpdate *ConfigUpdate `protobuf:"bytes,5,opt,name=config_update,json=configUpdate,proto3,oneof"`
}

func (*ServerMessage_HeartbeatAck) isServerMessage_Message() {}

func (*ServerMessage_CreatePeer) isServerMessage_Message() {}

func (*ServerMessage_RemovePeer) isServerMessage_Message() {}

func (*ServerMessage_UpdatePeer) isServerMessage_Message() {}

func (*ServerMessage_ConfigUpdate) isServerMessage_Message() {}

type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_proto_maranet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{17}
}

func (x *CommandAck) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PeerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	EventType     PeerEventType          `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=maranet.PeerEventType" json:"event_type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerEvent) Reset() {
	*x = PeerEvent{}
	mi := &file_proto_maranet_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerEvent) ProtoMessage() {}

func (x *PeerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerEvent.ProtoReflect.Descriptor instead.
func (*PeerEvent) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{18}
}

func (x *PeerEvent) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *PeerEvent) GetEventType() PeerEventType {
	if x != nil {
		return x.EventType
	}
	return PeerEventType_PEER_EVENT_UNSPECIFIED
}

func (x *PeerEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type NodeError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeError) Reset() {
	*x = NodeError{}
	mi := &file_proto_maranet_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeError) ProtoMessage() {}

func (x *NodeError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeError.ProtoReflect.Descriptor instead.
func (*NodeError) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{19}
}

func (x *NodeError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *NodeError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NodeError) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type ConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_proto_maranet_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{20}
}

func (x *ConfigUpdate) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type AddTunnelRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodePublicKey  string                 `protobuf:"bytes,2,opt,name=node_public_key,json=nodePublicKey,proto3" json:"node_public_key,omitempty"`
	NodeEndpoint   string                 `protobuf:"bytes,3,opt,name=node_endpoint,json=nodeEndpoint,proto3" json:"node_endpoint,omitempty"`
	AssignedSubnet string                 `protobuf:"bytes,4,opt,name=assigned_subnet,json=assignedSubnet,proto3" json:"assigned_subnet,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddTunnelRequest) Reset() {
	*x = AddTunnelRequest{}
	mi := &file_proto_maranet_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTunnelRequest) ProtoMessage() {}

func (x *AddTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTunnelRequest.ProtoReflect.Descriptor instead.
func (*AddTunnelRequest) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{21}
}

func (x *AddTunnelRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AddTunnelRequest) GetNodePublicKey() string {
	if x != nil {
		return x.NodePublicKey
	}
	return ""
}

func (x *AddTunnelRequest) GetNodeEndpoint() string {
	if x != nil {
		return x.NodeEndpoint
	}
	return ""
}

func (x *AddTunnelRequest) GetAssignedSubnet() string {
	if x != nil {
		return x.AssignedSubnet
	}
	return ""
}

type AddTunnelResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	GatewayPublicKey string                 `protobuf:"bytes,2,opt,name=gateway_public_key,json=gatewayPublicKey,proto3" json:"gateway_public_key,omitempty"`
	GatewayEndpoint  string                 `protobuf:"bytes,3,opt,name=gateway_endpoint,json=gatewayEndpoint,proto3" json:"gateway_endpoint,omitempty"`
	Error            string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddTunnelResponse) Reset() {
	*x = AddTunnelResponse{}
	mi := &file_proto_maranet_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTunnelResponse) ProtoMessage() {}

func (x *AddTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTunnelResponse.ProtoReflect.Descriptor instead.
func (*AddTunnelResponse) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{22}
}

func (x *AddTunnelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddTunnelResponse) GetGatewayPublicKey() string {
	if x != nil {
		return x.GatewayPublicKey
	}
	return ""
}

func (x *AddTunnelResponse) GetGatewayEndpoint() string {
	if x != nil {
		return x.GatewayEndpoint
	}
	return ""
}

func (x *AddTunnelResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RemoveTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodePublicKey string                 `protobuf:"bytes,2,opt,name=node_public_key,json=nodePublicKey,proto3" json:"node_public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTunnelRequest) Reset() {
	*x = RemoveTunnelRequest{}
	mi := &file_proto_maranet_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTunnelRequest) ProtoMessage() {}

func (x *RemoveTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTunnelRequest.ProtoReflect.Descriptor instead.
func (*RemoveTunnelRequest) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{23}
}

func (x *RemoveTunnelRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RemoveTunnelRequest) GetNodePublicKey() string {
	if x != nil {
		return x.NodePublicKey
	}
	return ""
}

type RemoveTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTunnelResponse) Reset() {
	*x = RemoveTunnelResponse{}
	mi := &file_proto_maranet_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTunnelResponse) ProtoMessage() {}

func (x *RemoveTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTunnelResponse.ProtoReflect.Descriptor instead.
func (*RemoveTunnelResponse) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{24}
}

func (x *RemoveTunnelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveTunnelResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GatewayStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveTunnels int32                  `protobuf:"varint,1,opt,name=active_tunnels,json=activeTunnels,proto3" json:"active_tunnels,omitempty"`
	TotalBytesRx  int64                  `protobuf:"varint,2,opt,name=total_bytes_rx,json=totalBytesRx,proto3" json:"total_bytes_rx,omitempty"`
	TotalBytesTx  int64                  `protobuf:"varint,3,opt,name=total_bytes_tx,json=totalBytesTx,proto3" json:"total_bytes_tx,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,4,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,5,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	UptimeSince   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=uptime_since,json=uptimeSince,proto3" json:"uptime_since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayStatus) Reset() {
	*x = GatewayStatus{}
	mi := &file_proto_maranet_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayStatus) ProtoMessage() {}

func (x *GatewayStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayStatus.ProtoReflect.Descriptor instead.
func (*GatewayStatus) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{25}
}

func (x *GatewayStatus) GetActiveTunnels() int32 {
	if x != nil {
		return x.ActiveTunnels
	}
	return 0
}

func (x *GatewayStatus) GetTotalBytesRx() int64 {
	if x != nil {
		return x.TotalBytesRx
	}
	return 0
}

func (x *GatewayStatus) GetTotalBytesTx() int64 {
	if x != nil {
		return x.TotalBytesTx
	}
	return 0
}

func (x *GatewayStatus) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *GatewayStatus) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *GatewayStatus) GetUptimeSince() *timestamppb.Timestamp {
	if x != nil {
		return x.UptimeSince
	}
	return nil
}

type TunnelStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelStatsRequest) Reset() {
	*x = TunnelStatsRequest{}
	mi := &file_proto_maranet_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelStatsRequest) ProtoMessage() {}

func (x *TunnelStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelStatsRequest.ProtoReflect.Descriptor instead.
func (*TunnelStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{26}
}

func (x *TunnelStatsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type TunnelStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	BytesRx       int64                  `protobuf:"varint,2,opt,name=bytes_rx,json=bytesRx,proto3" json:"bytes_rx,omitempty"`
	BytesTx       int64                  `protobuf:"varint,3,opt,name=bytes_tx,json=bytesTx,proto3" json:"bytes_tx,omitempty"`
	LastHandshake *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_handshake,json=lastHandshake,proto3" json:"last_handshake,omitempty"`
	Connected     bool                   `protobuf:"varint,5,opt,name=connected,proto3" json:"connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelStatsResponse) Reset() {
	*x = TunnelStatsResponse{}
	mi := &file_proto_maranet_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelStatsResponse) ProtoMessage() {}

func (x *TunnelStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maranet_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelStatsResponse.ProtoReflect.Descriptor instead.
func (*TunnelStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_maranet_proto_rawDescGZIP(), []int{27}
}

func (x *TunnelStatsResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TunnelStatsResponse) GetBytesRx() int64 {
	if x != nil {
		return x.BytesRx
	}
	return 0
}

func (x *TunnelStatsResponse) GetBytesTx() int64 {
	if x != nil {
		return x.BytesTx
	}
	return 0
}

func (x *TunnelStatsResponse) GetLastHandshake() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHandshake
	}
	return nil
}

func (x *TunnelStatsResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

var File_proto_maranet_proto protoreflect.FileDescriptor

const file_proto_maranet_proto_rawDesc = "" +
	"\n" +
	"\x13proto/maranet.proto\x12\amaranet\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x9a\x02\n" +
	"\x13RegisterNodeRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x1a\n" +
	"\bcapacity\x18\x05 \x01(\x05R\bcapacity\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x1a\n" +
	"\bplatform\x18\a \x01(\tR\bplatform\x12=\n" +
	"\fcapabilities\x18\b \x01(\v2\x19.maranet.NodeCapabilitiesR\fcapabilities\"\x96\x01\n" +
	"\x10NodeCapabilities\x12%\n" +
	"\x0ebandwidth_mbps\x18\x01 \x01(\x03R\rbandwidthMbps\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x03R\bmemoryMb\x12\x1b\n" +
	"\tcpu_cores\x18\x03 \x01(\x05R\bcpuCores\x12!\n" +
	"\fipv6_support\x18\x04 \x01(\bR\vipv6Support\"\x88\x02\n" +
	"\x14RegisterNodeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12*\n" +
	"\x11server_public_key\x18\x02 \x01(\tR\x0fserverPublicKey\x12'\n" +
	"\x0fserver_endpoint\x18\x03 \x01(\tR\x0eserverEndpoint\x12'\n" +
	"\x0fassigned_subnet\x18\x04 \x01(\tR\x0eassignedSubnet\x12#\n" +
	"\rtunnel_config\x18\x05 \x01(\tR\ftunnelConfig\x124\n" +
	"\x16heartbeat_interval_sec\x18\x06 \x01(\x05R\x14heartbeatIntervalSec\"\xa5\x02\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\factive_peers\x18\x02 \x01(\x05R\vactivePeers\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x04 \x01(\x01R\vmemoryUsage\x12\x19\n" +
	"\bbytes_rx\x18\x05 \x01(\x03R\abytesRx\x12\x19\n" +
	"\bbytes_tx\x18\x06 \x01(\x03R\abytesTx\x12%\n" +
	"\x0euptime_seconds\x18\a \x01(\x01R\ruptimeSeconds\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"{\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12B\n" +
	"\x10pending_commands\x18\x02 \x03(\v2\x17.maranet.PendingCommandR\x0fpendingCommands\"s\n" +
	"\x0ePendingCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.maranet.CommandTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\xe9\x01\n" +
	"\x11CreatePeerRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x0fsubscription_id\x18\x03 \x01(\tR\x0esubscriptionId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1f\n" +
	"\vallowed_ips\x18\x06 \x01(\tR\n" +
	"allowedIps\"\xe9\x01\n" +
	"\x12CreatePeerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\apeer_ip\x18\x02 \x01(\tR\x06peerIp\x12#\n" +
	"\rnode_endpoint\x18\x03 \x01(\tR\fnodeEndpoint\x12&\n" +
	"\x0fnode_public_key\x18\x04 \x01(\tR\rnodePublicKey\x12\x1f\n" +
	"\vdns_servers\x18\x05 \x01(\tR\n" +
	"dnsServers\x12\x1c\n" +
	"\tkeepalive\x18\x06 \x01(\x05R\tkeepalive\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"d\n" +
	"\x11RemovePeerRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"D\n" +
	"\x12RemovePeerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa6\x01\n" +
	"\x11UpdatePeerRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12@\n" +
	"\x0enew_expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fnewExpiresAt\"D\n" +
	"\x12UpdatePeerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"+\n" +
	"\x10ListPeersRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"<\n" +
	"\x11ListPeersResponse\x12'\n" +
	"\x05peers\x18\x01 \x03(\v2\x11.maranet.PeerInfoR\x05peers\"\xc0\x02\n" +
	"\bPeerInfo\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x0fsubscription_id\x18\x03 \x01(\tR\x0esubscriptionId\x12\x1f\n" +
	"\vallowed_ips\x18\x04 \x01(\tR\n" +
	"allowedIps\x12\x19\n" +
	"\bbytes_rx\x18\x05 \x01(\x03R\abytesRx\x12\x19\n" +
	"\bbytes_tx\x18\x06 \x01(\x03R\abytesTx\x12A\n" +
	"\x0elast_handshake\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rlastHandshake\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x85\x02\n" +
	"\vNodeMessage\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x129\n" +
	"\theartbeat\x18\x02 \x01(\v2\x19.maranet.HeartbeatRequestH\x00R\theartbeat\x126\n" +
	"\vcommand_ack\x18\x03 \x01(\v2\x13.maranet.CommandAckH\x00R\n" +
	"commandAck\x123\n" +
	"\n" +
	"peer_event\x18\x04 \x01(\v2\x12.maranet.PeerEventH\x00R\tpeerEvent\x12*\n" +
	"\x05error\x18\x05 \x01(\v2\x12.maranet.NodeErrorH\x00R\x05errorB\t\n" +
	"\amessage\"\xd8\x02\n" +
	"\rServerMessage\x12A\n" +
	"\rheartbeat_ack\x18\x01 \x01(\v2\x1a.maranet.HeartbeatResponseH\x00R\fheartbeatAck\x12=\n" +
	"\vcreate_peer\x18\x02 \x01(\v2\x1a.maranet.CreatePeerRequestH\x00R\n" +
	"createPeer\x12=\n" +
	"\vremove_peer\x18\x03 \x01(\v2\x1a.maranet.RemovePeerRequestH\x00R\n" +
	"removePeer\x12=\n" +
	"\vupdate_peer\x18\x04 \x01(\v2\x1a.maranet.UpdatePeerRequestH\x00R\n" +
	"updatePeer\x12<\n" +
	"\rconfig_update\x18\x05 \x01(\v2\x15.maranet.ConfigUpdateH\x00R\fconfigUpdateB\t\n" +
	"\amessage\"[\n" +
	"\n" +
	"CommandAck\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x9b\x01\n" +
	"\tPeerEvent\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x125\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2\x16.maranet.PeerEventTypeR\teventType\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"S\n" +
	"\tNodeError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"\x84\x01\n" +
	"\fConfigUpdate\x129\n" +
	"\x06config\x18\x01 \x03(\v2!.maranet.ConfigUpdate.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x01\n" +
	"\x10AddTunnelRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12&\n" +
	"\x0fnode_public_key\x18\x02 \x01(\tR\rnodePublicKey\x12#\n" +
	"\rnode_endpoint\x18\x03 \x01(\tR\fnodeEndpoint\x12'\n" +
	"\x0fassigned_subnet\x18\x04 \x01(\tR\x0eassignedSubnet\"\x9c\x01\n" +
	"\x11AddTunnelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\x12gateway_public_key\x18\x02 \x01(\tR\x10gatewayPublicKey\x12)\n" +
	"\x10gateway_endpoint\x18\x03 \x01(\tR\x0fgatewayEndpoint\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"V\n" +
	"\x13RemoveTunnelRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12&\n" +
	"\x0fnode_public_key\x18\x02 \x01(\tR\rnodePublicKey\"F\n" +
	"\x14RemoveTunnelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x81\x02\n" +
	"\rGatewayStatus\x12%\n" +
	"\x0eactive_tunnels\x18\x01 \x01(\x05R\ractiveTunnels\x12$\n" +
	"\x0etotal_bytes_rx\x18\x02 \x01(\x03R\ftotalBytesRx\x12$\n" +
	"\x0etotal_bytes_tx\x18\x03 \x01(\x03R\ftotalBytesTx\x12\x1b\n" +
	"\tcpu_usage\x18\x04 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x05 \x01(\x01R\vmemoryUsage\x12=\n" +
	"\fuptime_since\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vuptimeSince\"-\n" +
	"\x12TunnelStatsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xc5\x01\n" +
	"\x13TunnelStatsResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bbytes_rx\x18\x02 \x01(\x03R\abytesRx\x12\x19\n" +
	"\bbytes_tx\x18\x03 \x01(\x03R\abytesTx\x12A\n" +
	"\x0elast_handshake\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHandshake\x12\x1c\n" +
	"\tconnected\x18\x05 \x01(\bR\tconnected*\xbc\x01\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13COMMAND_CREATE_PEER\x10\x01\x12\x17\n" +
	"\x13COMMAND_REMOVE_PEER\x10\x02\x12\x17\n" +
	"\x13COMMAND_UPDATE_PEER\x10\x03\x12\x19\n" +
	"\x15COMMAND_UPDATE_CONFIG\x10\x04\x12\x13\n" +
	"\x0fCOMMAND_RESTART\x10\x05\x12\x14\n" +
	"\x10COMMAND_SHUTDOWN\x10\x06*\x83\x01\n" +
	"\rPeerEventType\x12\x1a\n" +
	"\x16PEER_EVENT_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePEER_CONNECTED\x10\x01\x12\x15\n" +
	"\x11PEER_DISCONNECTED\x10\x02\x12\x10\n" +
	"\fPEER_EXPIRED\x10\x03\x12\x19\n" +
	"\x15PEER_HANDSHAKE_FAILED\x10\x042\xfe\x03\n" +
	"\vNodeService\x12K\n" +
	"\fRegisterNode\x12\x1c.maranet.RegisterNodeRequest\x1a\x1d.maranet.RegisterNodeResponse\x12F\n" +
	"\tHeartbeat\x12\x19.maranet.HeartbeatRequest\x1a\x1a.maranet.HeartbeatResponse(\x010\x01\x12E\n" +
	"\n" +
	"CreatePeer\x12\x1a.maranet.CreatePeerRequest\x1a\x1b.maranet.CreatePeerResponse\x12E\n" +
	"\n" +
	"RemovePeer\x12\x1a.maranet.RemovePeerRequest\x1a\x1b.maranet.RemovePeerResponse\x12E\n" +
	"\n" +
	"UpdatePeer\x12\x1a.maranet.UpdatePeerRequest\x1a\x1b.maranet.UpdatePeerResponse\x12B\n" +
	"\tListPeers\x12\x19.maranet.ListPeersRequest\x1a\x1a.maranet.ListPeersResponse\x12A\n" +
	"\rCommandStream\x12\x14.maranet.NodeMessage\x1a\x16.maranet.ServerMessage(\x010\x012\xab\x02\n" +
	"\x0eGatewayService\x12B\n" +
	"\tAddTunnel\x12\x19.maranet.AddTunnelRequest\x1a\x1a.maranet.AddTunnelResponse\x12K\n" +
	"\fRemoveTunnel\x12\x1c.maranet.RemoveTunnelRequest\x1a\x1d.maranet.RemoveTunnelResponse\x12;\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x16.maranet.GatewayStatus\x12K\n" +
	"\x0eGetTunnelStats\x12\x1b.maranet.TunnelStatsRequest\x1a\x1c.maranet.TunnelStatsResponseB$Z\"github.com/maranet/proto;maranetpbb\x06proto3"

var (
	file_proto_maranet_proto_rawDescOnce sync.Once
	file_proto_maranet_proto_rawDescData []byte
)

func file_proto_maranet_proto_rawDescGZIP() []byte {
	file_proto_maranet_proto_rawDescOnce.Do(func() {
		file_proto_maranet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_maranet_proto_rawDesc), len(file_proto_maranet_proto_rawDesc)))
	})
	return file_proto_maranet_proto_rawDescData
}

var file_proto_maranet_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_maranet_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_maranet_proto_goTypes = []any{
	(CommandType)(0),              // 0: maranet.CommandType
	(PeerEventType)(0),            // 1: maranet.PeerEventType
	(*RegisterNodeRequest)(nil),   // 2: maranet.RegisterNodeRequest
	(*NodeCapabilities)(nil),      // 3: maranet.NodeCapabilities
	(*RegisterNodeResponse)(nil),  // 4: maranet.RegisterNodeResponse
	(*HeartbeatRequest)(nil),      // 5: maranet.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 6: maranet.HeartbeatResponse
	(*PendingCommand)(nil),        // 7: maranet.PendingCommand
	(*CreatePeerRequest)(nil),     // 8: maranet.CreatePeerRequest
	(*CreatePeerResponse)(nil),    // 9: maranet.CreatePeerResponse
	(*RemovePeerRequest)(nil),     // 10: maranet.RemovePeerRequest
	(*RemovePeerResponse)(nil),    // 11: maranet.RemovePeerResponse
	(*UpdatePeerRequest)(nil),     // 12: maranet.UpdatePeerRequest
	(*UpdatePeerResponse)(nil),    // 13: maranet.UpdatePeerResponse
	(*ListPeersRequest)(nil),      // 14: maranet.ListPeersRequest
	(*ListPeersResponse)(nil),     // 15: maranet.ListPeersResponse
	(*PeerInfo)(nil),              // 16: maranet.PeerInfo
	(*NodeMessage)(nil),           // 17: maranet.NodeMessage
	(*ServerMessage)(nil),         // 18: maranet.ServerMessage
	(*CommandAck)(nil),            // 19: maranet.CommandAck
	(*PeerEvent)(nil),             // 20: maranet.PeerEvent
	(*NodeError)(nil),             // 21: maranet.NodeError
	(*ConfigUpdate)(nil),          // 22: maranet.ConfigUpdate
	(*AddTunnelRequest)(nil),      // 23: maranet.AddTunnelRequest
	(*AddTunnelResponse)(nil),     // 24: maranet.AddTunnelResponse
	(*RemoveTunnelRequest)(nil),   // 25: maranet.RemoveTunnelRequest
	(*RemoveTunnelResponse)(nil),  // 26: maranet.RemoveTunnelResponse
	(*GatewayStatus)(nil),         // 27: maranet.GatewayStatus
	(*TunnelStatsRequest)(nil),    // 28: maranet.TunnelStatsRequest
	(*TunnelStatsResponse)(nil),   // 29: maranet.TunnelStatsResponse
	nil,                           // 30: maranet.ConfigUpdate.ConfigEntry
	(*timestamppb.Timestamp)(nil), // 31: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 32: google.protobuf.Empty
}
var file_proto_maranet_proto_depIdxs = []int32{
	3,  // 0: maranet.RegisterNodeRequest.capabilities:type_name -> maranet.NodeCapabilities
	31, // 1: maranet.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 2: maranet.HeartbeatResponse.pending_commands:type_name -> maranet.PendingCommand
	0,  // 3: maranet.PendingCommand.type:type_name -> maranet.CommandType
	31, // 4: maranet.CreatePeerRequest.expires_at:type_name -> google.protobuf.Timestamp
	31, // 5: maranet.UpdatePeerRequest.new_expires_at:type_name -> google.protobuf.Timestamp
	16, // 6: maranet.ListPeersResponse.peers:type_name -> maranet.PeerInfo
	31, // 7: maranet.PeerInfo.last_handshake:type_name -> google.protobuf.Timestamp
	31, // 8: maranet.PeerInfo.expires_at:type_name -> google.protobuf.Timestamp
	5,  // 9: maranet.NodeMessage.heartbeat:type_name -> maranet.HeartbeatRequest
	19, // 10: maranet.NodeMessage.command_ack:type_name -> maranet.CommandAck
	20, // 11: maranet.NodeMessage.peer_event:type_name -> maranet.PeerEvent
	21, // 12: maranet.NodeMessage.error:type_name -> maranet.NodeError
	6,  // 13: maranet.ServerMessage.heartbeat_ack:type_name -> maranet.HeartbeatResponse
	8,  // 14: maranet.ServerMessage.create_peer:type_name -> maranet.CreatePeerRequest
	10, // 15: maranet.ServerMessage.remove_peer:type_name -> maranet.RemovePeerRequest
	12, // 16: maranet.ServerMessage.update_peer:type_name -> maranet.UpdatePeerRequest
	22, // 17: maranet.ServerMessage.config_update:type_name -> maranet.ConfigUpdate
	1,  // 18: maranet.PeerEvent.event_type:type_name -> maranet.PeerEventType
	31, // 19: maranet.PeerEvent.timestamp:type_name -> google.protobuf.Timestamp
	30, // 20: maranet.ConfigUpdate.config:type_name -> maranet.ConfigUpdate.ConfigEntry
	31, // 21: maranet.GatewayStatus.uptime_since:type_name -> google.protobuf.Timestamp
	31, // 22: maranet.TunnelStatsResponse.last_handshake:type_name -> google.protobuf.Timestamp
	2,  // 23: maranet.NodeService.RegisterNode:input_type -> maranet.RegisterNodeRequest
	5,  // 24: maranet.NodeService.Heartbeat:input_type -> maranet.HeartbeatRequest
	8,  // 25: maranet.NodeService.CreatePeer:input_type -> maranet.CreatePeerRequest
	10, // 26: maranet.NodeService.RemovePeer:input_type -> maranet.RemovePeerRequest
	12, // 27: maranet.NodeService.UpdatePeer:input_type -> maranet.UpdatePeerRequest
	14, // 28: maranet.NodeService.ListPeers:input_type -> maranet.ListPeersRequest
	17, // 29: maranet.NodeService.CommandStream:input_type -> maranet.NodeMessage
	23, // 30: maranet.GatewayService.AddTunnel:input_type -> maranet.AddTunnelRequest
	25, // 31: maranet.GatewayService.RemoveTunnel:input_type -> maranet.RemoveTunnelRequest
	32, // 32: maranet.GatewayService.GetStatus:input_type -> google.protobuf.Empty
	28, // 33: maranet.GatewayService.GetTunnelStats:input_type -> maranet.TunnelStatsRequest
	4,  // 34: maranet.NodeService.RegisterNode:output_type -> maranet.RegisterNodeResponse
	6,  // 35: maranet.NodeService.Heartbeat:output_type -> maranet.HeartbeatResponse
	9,  // 36: maranet.NodeService.CreatePeer:output_type -> maranet.CreatePeerResponse
	11, // 37: maranet.NodeService.RemovePeer:output_type -> maranet.RemovePeerResponse
	13, // 38: maranet.NodeService.UpdatePeer:output_type -> maranet.UpdatePeerResponse
	15, // 39: maranet.NodeService.ListPeers:output_type -> maranet.ListPeersResponse
	18, // 40: maranet.NodeService.CommandStream:output_type -> maranet.ServerMessage
	24, // 41: maranet.GatewayService.AddTunnel:output_type -> maranet.AddTunnelResponse
	26, // 42: maranet.GatewayService.RemoveTunnel:output_type -> maranet.RemoveTunnelResponse
	27, // 43: maranet.GatewayService.GetStatus:output_type -> maranet.GatewayStatus
	29, // 44: maranet.GatewayService.GetTunnelStats:output_type -> maranet.TunnelStatsResponse
	34, // [34:45] is the sub-list for method output_type
	23, // [23:34] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_proto_maranet_proto_init() }
func file_proto_maranet_proto_init() {
	if File_proto_maranet_proto != nil {
		return
	}
	file_proto_maranet_proto_msgTypes[15].OneofWrappers = []any{
		(*NodeMessage_Heartbeat)(nil),
		(*NodeMessage_CommandAck)(nil),
		(*NodeMessage_PeerEvent)(nil),
		(*NodeMessage_Error)(nil),
	}
	file_proto_maranet_proto_msgTypes[16].OneofWrappers = []any{
		(*ServerMessage_HeartbeatAck)(nil),
		(*ServerMessage_CreatePeer)(nil),
		(*ServerMessage_RemovePeer)(nil),
		(*ServerMessage_UpdatePeer)(nil),
		(*ServerMessage_ConfigUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_maranet_proto_rawDesc), len(file_proto_maranet_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_maranet_proto_goTypes,
		DependencyIndexes: file_proto_maranet_proto_depIdxs,
		EnumInfos:         file_proto_maranet_proto_enumTypes,
		MessageInfos:      file_proto_maranet_proto_msgTypes,
	}.Build()
	File_proto_maranet_proto = out.File
	file_proto_maranet_proto_goTypes = nil
	file_proto_maranet_proto_depIdxs = nil
}
